### ISSUE TITLE
Bug: you can save empty groups

### ISSUE THREAD

**Issue by Austintacious** [wannabefro/secret_santa_ruby#5]
When prompted by the menu, you can save a group without creating one.

**Comment by wannabefro** [comment]
is it really a bug to be able to save an empty group? what happens if you want to just set it up for later without adding in any participants. it still saves with a group. it just has no participants. what do you think it should do instead?

**Comment by Austintacious** [comment]
We don't like name-squatting, but fineeee. You win... for now.

**Comment by wannabefro** [comment]
closing ... for now
